import { BaseEditor, NodeEntry } from 'slate'
import { HistoryEditor } from 'slate-history'
import { ReactEditor } from 'slate-react'
import { FindDecoration } from '@lib/slate-plugins/decorations'

// globals.d.ts
declare global {
  interface Window {
    env: any
  }
}

export {}

export type DocumentData = {
  _id: string
  title: string
  content: string
  comments: CommentData[]
  lastUpdated: number
  userId: string
  canEdit?: boolean
  canComment?: boolean
  parentId?: string | 'root' // ID of the parent folder, 'root' means root level
  folderIndex: number // Position within the parent folder, lower numbers appear first
}

export type CommentData = {
  id: string
  timestamp: number
  content: string
}

export type ShareUser = {
  email: string
  permission: UserPermission
}

export type PermissionData = {
  documentId: string
  ownerId: string
  globalPermission: UserPermission
  users: ShareUser[]
}

export type VersionData = {
  id: string
  documentId: string
  ownerId: string
  name?: string
  createdAt: number
  autoGenerated: boolean
  wordCount: number
  content: string
}

export enum UserPermission {
  View = 'View',
  Comment = 'Comment',
  Edit = 'Edit',
  None = 'None',
}

export type AnimationState = 'Active' | 'Complete' | 'Inactive'

export type WhetstoneEditor = BaseEditor & ReactEditor & HistoryEditor & {
  decorations: FindDecoration[]
  setDecorations: (decorations: FindDecoration[]) => void
  decorate?: (entry: NodeEntry) => FindDecoration[]
}

export type FolderData = {
  _id: string
  title: string
  parentId?: string | 'root' // ID of the parent folder, 'root' means root level
  userId: string
  lastUpdated: number
  folderIndex: number // Position within the parent folder, lower numbers appear first
}
