import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <div className='gradient absolute top-0 left-0 h-screen w-screen z-[-1]'/>
        <title>Whetstone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={`${styles.title} text-black/[.4]`}>
          whetstone
        </h1>
        <h2 className="title">
          The writing app for editing.
        </h2>

        <h1 className="title">
          <a href="/documents">Get Started</a>
        </h1>
      </main>
    </div>
  )
}

export default Home
